import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

/**
 * The rule that matters most here is the `/packages/engine` boundary at the bottom of this file.
 *
 * The engine is the code that ships inside every exported project. If a UI framework, a state
 * library or editor code ever reaches it through an import, exports silently stop working — so it
 * is enforced mechanically from commit #1 rather than by memory. See GUIDE.md section 7, risk 1.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/.turbo/**',
      '**/coverage/**',
      // Generated by `pnpm ingest-assets`, including third-party decoder builds.
      'generated/**',
      // Playwright's leftovers. They contain whole extracted exports — minified engine bundles and
      // generated `main.js` files — which are lint targets only in the sense that a zip is.
      '**/test-results/**',
      '**/playwright-report/**',
      // Builds published to the local share service. Whole exports — minified engine bundles and
      // third-party decoders — which are lint targets only in the sense that a zip is.
      '**/.hela-shared*/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      eqeqeq: ['error', 'smart'],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // The rules-of-hooks and dependency checks earn their keep in the editor: a stale dependency
    // array is what made the viewport render placeholder boxes forever in Sprint 3.
    files: ['apps/editor/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },
  {
    files: ['packages/engine/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                'react',
                'react-*',
                '@react-three/*',
                'zustand',
                'zustand/*',
                'immer',
                '@helaengine/editor',
                '@helaengine/editor/*',
                '**/apps/editor/**',
              ],
              message:
                'The engine runs standalone inside exported projects. It must not import UI frameworks, editor state libraries, or editor code. Move this logic into /apps/editor and call the engine from there.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['packages/schema/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['three', 'three/*', 'react', 'react-*', '@helaengine/*'],
              message:
                'The schema package is the shared contract between engine, editor, exporter and API. It must stay dependency-free apart from zod.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['packages/export/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                'three',
                'three/*',
                'react',
                'react-*',
                '@react-three/*',
                'jszip',
                'zustand',
                '@helaengine/editor',
                '@helaengine/editor/*',
                '**/apps/editor/**',
              ],
              message:
                'The exporter has to run without a browser — the smoke harness builds real exports in Node, and the API will eventually build them on a server. Keep the DOM parts (zipping, downloading, fetching from the asset library) in /apps/editor/src/export.',
            },
          ],
        },
      ],
    },
  },
  {
    // Pipeline scripts are CLIs and services log to stdout — in both cases the console output is
    // the interface an operator reads, not a debugging leftover.
    files: ['tools/**/*.ts', 'apps/share/src/index.ts', 'apps/realtime/src/index.ts'],
    rules: {
      'no-console': 'off',
    },
  },
  {
    // The benchmark is a Node script that drives a browser, so it legitimately touches both
    // environments: `process` and `console` on one side of the wire, `window` and
    // `requestAnimationFrame` inside the `page.evaluate` callbacks on the other.
    files: ['tools/**/*.mjs'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        URL: 'readonly',
        window: 'readonly',
        indexedDB: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
    },
  },
  {
    files: ['**/*.test.ts', 'scripts/**/*.ts', '**/vite.config.ts'],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
);
