import type { z } from 'zod';

/**
 * The behaviour reference, read out of the engine's own schemas.
 *
 * The plan asks for "full behavior reference (each built-in behavior type + its params, with
 * examples)". Written by hand, that page is correct on the day it is written and wrong by the third
 * time somebody adds a parameter — and a reference that is *subtly* wrong is worse than none,
 * because people trust it and then debug the wrong thing for an hour.
 *
 * So it is generated by walking the Zod schemas the engine already validates against. There is
 * exactly one description of what `chaseOnSight` accepts, it lives beside the code that enforces
 * it, and a parameter added without a default shows up here on the next run.
 *
 * **What this does not do:** it reads Zod's internals (`_def`), which are not a public API. That is
 * a real cost and the reason the walker is small, total, and falls back to the type name it cannot
 * describe rather than throwing. A Zod major version will need this file revisited; a generated
 * page that fails loudly on upgrade is still better than a hand-written one that fails silently
 * every sprint.
 */

export interface ParamDoc {
  name: string;
  /** A short human-readable type, e.g. `number`, `"box" | "sphere"`, `number[]`. */
  type: string;
  /** Absent when the parameter is required. */
  defaultValue?: string;
  optional: boolean;
  /** Range or length constraints worth knowing before you type a value. */
  constraints: string[];
  /** The TSDoc-style `.describe()` text, when the schema carries one. */
  description?: string;
}

export interface BehaviourDoc {
  type: string;
  label: string;
  description: string;
  params: ParamDoc[];
}

/** Unwraps the wrappers Zod stacks around a type, remembering what it found. */
interface Unwrapped {
  inner: z.ZodTypeAny;
  optional: boolean;
  defaultValue?: unknown;
  description?: string;
}

function unwrap(schema: z.ZodTypeAny): Unwrapped {
  let current = schema;
  let optional = false;
  let defaultValue: unknown;
  let description: string | undefined = current._def.description;

  // Bounded rather than `while (true)`: a cyclic schema would otherwise hang the build, and a
  // documentation generator that hangs is worse than one that gives up.
  for (let depth = 0; depth < 12; depth += 1) {
    const def = current._def as {
      typeName?: string;
      innerType?: z.ZodTypeAny;
      defaultValue?: () => unknown;
    };
    description ??= current._def.description;

    if (def.typeName === 'ZodOptional' || def.typeName === 'ZodNullable') {
      optional = true;
      current = def.innerType!;
      continue;
    }
    if (def.typeName === 'ZodDefault') {
      defaultValue = def.defaultValue?.();
      optional = true;
      current = def.innerType!;
      continue;
    }
    break;
  }

  return {
    inner: current,
    optional,
    ...(defaultValue === undefined ? {} : { defaultValue }),
    ...(description === undefined ? {} : { description }),
  };
}

/** A readable type name. Falls back to Zod's own label for anything it does not know. */
export function describeType(schema: z.ZodTypeAny): string {
  const def = schema._def as {
    typeName?: string;
    values?: string[];
    type?: z.ZodTypeAny;
    options?: z.ZodTypeAny[];
    value?: unknown;
  };

  switch (def.typeName) {
    case 'ZodString':
      return 'string';
    case 'ZodNumber':
      return 'number';
    case 'ZodBoolean':
      return 'boolean';
    case 'ZodEnum':
      return (def.values ?? []).map((value) => `"${value}"`).join(' | ');
    case 'ZodLiteral':
      return typeof def.value === 'string' ? `"${String(def.value)}"` : String(def.value);
    case 'ZodArray':
      return `${describeType(def.type!)}[]`;
    case 'ZodTuple':
      return `[${((def as { items?: z.ZodTypeAny[] }).items ?? []).map(describeType).join(', ')}]`;
    case 'ZodUnion':
      return (def.options ?? []).map(describeType).join(' | ');
    case 'ZodObject':
      return 'object';
    case 'ZodRecord':
      return 'record';
    default:
      return def.typeName?.replace(/^Zod/, '').toLowerCase() ?? 'unknown';
  }
}

/** Range and length limits, as short phrases rather than a table nobody reads. */
export function describeConstraints(schema: z.ZodTypeAny): string[] {
  const checks =
    (schema._def as { checks?: Array<{ kind: string; value?: unknown }> }).checks ?? [];
  const said: string[] = [];

  for (const check of checks) {
    switch (check.kind) {
      case 'min':
        said.push(`at least ${String(check.value)}`);
        break;
      case 'max':
        said.push(`at most ${String(check.value)}`);
        break;
      case 'int':
        said.push('whole numbers only');
        break;
      case 'nonnegative':
        said.push('cannot be negative');
        break;
      case 'positive':
        said.push('must be positive');
        break;
      default:
        break;
    }
  }

  return said;
}

export function documentParams(schema: z.ZodTypeAny): ParamDoc[] {
  const shape = (schema._def as { shape?: () => Record<string, z.ZodTypeAny> }).shape?.();
  if (!shape) return [];

  return Object.entries(shape).map(([name, field]) => {
    const { inner, optional, defaultValue, description } = unwrap(field);
    return {
      name,
      type: describeType(inner),
      optional,
      constraints: describeConstraints(inner),
      ...(defaultValue === undefined ? {} : { defaultValue: JSON.stringify(defaultValue) }),
      ...(description === undefined ? {} : { description }),
    };
  });
}

export interface BehaviourSource {
  type: string;
  label: string;
  description: string;
  params: z.ZodTypeAny;
}

export function documentBehaviours(sources: readonly BehaviourSource[]): BehaviourDoc[] {
  return sources
    .map((source) => ({
      type: source.type,
      label: source.label,
      description: source.description,
      params: documentParams(source.params),
    }))
    .sort((a, b) => a.type.localeCompare(b.type));
}

/** A worked example, built from the schema's own defaults so it is always valid. */
function exampleFor(behaviour: BehaviourDoc): string {
  const filled = behaviour.params
    .filter((param) => param.defaultValue !== undefined || !param.optional)
    .slice(0, 4)
    .map((param) => `      "${param.name}": ${param.defaultValue ?? placeholderFor(param)}`);

  return [
    '```json',
    '{',
    `  "type": "${behaviour.type}",`,
    '  "params": {',
    filled.join(',\n').replace(/^ {6}/gm, '    '),
    '  }',
    '}',
    '```',
  ].join('\n');
}

function placeholderFor(param: ParamDoc): string {
  if (param.type === 'number') return '1';
  if (param.type === 'boolean') return 'true';
  if (param.type.startsWith('"')) return param.type.split(' | ')[0]!;
  if (param.type.endsWith('[]')) return '[]';
  return '"…"';
}

export function renderMarkdown(behaviours: readonly BehaviourDoc[]): string {
  const lines: string[] = [
    '# Behaviour reference',
    '',
    '<!-- Generated by `pnpm gen-docs`. Do not edit by hand — edit the schema and re-run. -->',
    '',
    'Every behaviour a scene can attach to an object, with the parameters it accepts.',
    '',
    "**This page is generated from the engine's own schemas**, which are the same schemas that",
    'validate a scene at load time. There is no second description of what `chaseOnSight` accepts',
    'that could disagree with the first. A parameter added to the code appears here on the next',
    '`pnpm gen-docs`, and CI fails if somebody forgets to run it.',
    '',
    'A behaviour is **data, never code**. The document names a `type` and carries plain `params`;',
    'there are no expression strings and nothing is interpreted. A scene written by a newer build',
    'still opens in an older one — the unknown behaviour is reported and skipped rather than making',
    'the whole scene unopenable.',
    '',
    '## Contents',
    '',
    ...behaviours.map(
      (behaviour) =>
        `- [\`${behaviour.type}\`](#${behaviour.type.toLowerCase()}) — ${behaviour.label}`,
    ),
    '',
  ];

  for (const behaviour of behaviours) {
    lines.push(`## ${behaviour.type}`, '', `**${behaviour.label}.** ${behaviour.description}`, '');

    if (behaviour.params.length === 0) {
      lines.push('Takes no parameters.', '');
    } else {
      lines.push('| Parameter | Type | Default | Notes |', '| --- | --- | --- | --- |');
      for (const param of behaviour.params) {
        const notes = [param.description, ...param.constraints].filter(Boolean).join('; ');
        lines.push(
          `| \`${param.name}\` | \`${param.type}\` | ` +
            `${param.defaultValue === undefined ? (param.optional ? '—' : '**required**') : `\`${param.defaultValue}\``} | ` +
            `${notes || '—'} |`,
        );
      }
      lines.push('', '### Example', '', exampleFor(behaviour), '');
    }
  }

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n')}\n`;
}
